version: '3.8'

services: 
  db:
    image: mysql:8.0.26
    restart: always
    # command: --lower_case_table_names=1
    environment:
      - MYSQL_DATABASE=tutorialdb
      - MYSQL_USER=chitrang
      - MYSQL_PASSWORD=test123
      - MYSQL_ROOT_PASSWORD=test123
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000  
    env_file: 
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static:/static
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend      

volumes: 
  dbdata:
  static: